[loggers]
keys=root, archive, remotePC

[handlers]
keys=fileHandler, streamHandler, archiveFileHandler, remotePCFileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=INFO
handlers=fileHandler, streamHandler

[logger_archive]
level=INFO
handlers=archiveFileHandler, streamHandler
qualname=archive
propagate=0

[logger_remotePC]
level=INFO
handlers=remotePCFileHandler, streamHandler
qualname=remotePC
propagate=0

[handler_fileHandler]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simpleFormatter
# 🌟 最後面加上 , True 開啟延遲開檔
args=('app.log', 'a', 1048576, 3, 'utf-8', True)

[handler_archiveFileHandler]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simpleFormatter
# 🌟 最後面加上 , True 開啟延遲開檔
args=('archive.log', 'a', 1048576, 3, 'utf-8', True)

[handler_remotePCFileHandler]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=simpleFormatter
# 🌟 最後面加上 , True 開啟延遲開檔
args=('remote_pc.log', 'a', 1048576, 3, 'utf-8', True)

[handler_streamHandler]
class=StreamHandler
level=INFO
formatter=simpleFormatter
args=()

[formatter_simpleFormatter]
format=[%(asctime)s] - [%(levelname)s]: %(message)s
datefmt=%I:%M:%S %p